### ISSUE TITLE
Trzeba przemyśleć encje. 

### ISSUE THREAD

**Issue by lumat18** [lumat18/tennistico#18]
no można trzymać win loss w encjach, bo zapytanie do bazy które będzie sprawdzało wynik i agregowało count() winów to może troszkę hardkor być

_Originally posted by @bartekmat in https://github.com/lumat18/tennistico/pull/14#issuecomment-643828232_

**Comment by serwacy** [comment]
a może zrobić enuma, który przewidzi każdy możliwy wynik? : )
a tak serio to na pewno będzie trzeba przemyśleć sprawę score'ów, na razie wyglądają tak a nie inaczej, bo po prostu ich jeszcze nie obrabialiśmy

**Comment by lumat18** [comment]
Pomysł: dodać do Playera pole Ranking z polami Wins, Losses i RankingPoints, po rozegraniu gry nalicza się win albo loss i dolicza ranking points.
